url: http://www.nlp.town/

# Site settings
title: NLP Town - NLP Consultancy and Software Development
email: yves@nlp.town
description: "NLP Town provides Natural Language Processing consultancy and development."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fc6420
  secondary: fec503  
  secondary-dark: 333

# Owner/author information
owner:
  name:           Yves Peirsman
  avatar:         yves
  bio:            Natural Language Processing Enthusiast at <a href="http://www.nlp.town">NLP Town</a>.
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        yvespeirsman
  linkedin:     yvespeirsman

# Team names, titles and social links
people:
- name: Yves Peirsman
  pic: yves
  position: NLP Expert
  social:
    - title: twitter
      url: https://twitter.com/yvespeirsman
    - title: linkedin
      url: https://www.linkedin.com/in/yvespeirsman

- name: Johan Leys
  pic: johan
  position: Software Architect

- name: Adriaan Lemmens
  pic: adriaan
  position: Computational Linguist

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/nlptown

# Postal address (add as many lines as necessary)
address:
  - line: Tervuursevest 21
  - line: 3001 Leuven

# Build settings
markdown: kramdown
permalink: pretty

# Analytics and webmaster tools stuff goes here
google_analytics: UA-105530786-1
