title:            NLP Town
description:      Natural Language Processing Consultancy and Development.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://www.nlp.town
disqus_shortname: nlp-town

# Owner/author information
owner:
  name:           Yves Peirsman
  avatar:         bio-photo.jpg
  bio:            Natural Language Processing Enthusiast at <a href="http://www.nlp.town">NLP Town</a>.
  email:
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:	  yvespeirsman
  facebook:
  github:
  stackoverflow:
  linkedin:	yvespeirsman
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:  

# Team names, titles and social links
people:
- name: Yves Peirsman
  pic: yves
  position: NLP Expert
  social:
    - title: twitter
      url: https://twitter.com/yvespeirsman
    - title: linkedin
      url: https://www.linkedin.com/in/yvespeirsman

- name: Johan Leys
  pic: johan
  position: Software Architect

- name: Adriaan Lemmens
  pic: adriaan
  position: Computational Linguist

# Analytics and webmaster tools stuff goes here
google_analytics:  UA-105530786-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: All Posts
    url: /blog/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
#pygments:    true
#highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  ternary: 10c3d3

# Footer settings
footer:
  copyright: Yves Peirsman
  location: Location
  social: Around the Web
  credits: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/yvespeirsman
  - title: linkedin
    url: http://linkedin.com/in/yvespeirsman
  - title: google-plus
    url: http://plus.google.com/+YvesPeirsman

# Postal address (add as many lines as necessary)
address:
  - line: Langelostraat 11 
  - line: 3212 Lubbeek
  - line: Belgium

# Credits content
credits: 'Get in touch via the channels to the left<br>or +32 485 024334'

