url: https://y7kim.github.io
baseurl: http://www.nlp.town/

# Site settings
title: NLP Town - NLP Consultancy and Software Development
email: yves@nlp.town
description: "NLP Town provides Natural Language Processing consultancy and development."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fc6420
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Yves Peirsman
  pic: 1
  position: NLP Expert
  social:
    - title: twitter
      url: https://twitter.com/yvespeirsman
    - title: linkedin
      url: https://www.linkedin.com/in/yvespeirsman

- name: Johan Leys
  pic: 2
  position: Software Engineer

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/nlptown

# Postal address (add as many lines as necessary)
address:
  - line: Tervuursevest 21
  - line: 3001 Leuven

# Build settings
markdown: kramdown
permalink: pretty
