url: https://y7kim.github.io
baseurl: http://www.nlp.town/

# Site settings
title: nlp.town
email: yves@nlp.town
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fc6420
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Yves Peirsman
  pic: 1
  position: NLP Expert
  social:
    - title: twitter
      url: https://twitter.com/yvespeirsman
    - title: linkedin
      url: https://www.linkedin.com/in/yvespeirsman

- name: Johan Leys
  pic: 2
  position: Software Engineer

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/nlptown

# Postal address (add as many lines as necessary)
address:
  - line: Tervuursevest 21
  - line: 3001 Leuven

# Build settings
markdown: kramdown
permalink: pretty
